"""初始 schema：八类核心对象 + 产品侧扩展表 + 治理表

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-09

由 metadata 自动生成后逐行审过。要点：

- 所有时间列为 timestamptz（Base.type_annotation_map 全局映射），naive datetime
  在应用层由 app.core.timeutil 拦截。
- 数据库层固化了六条产品红线：signal 不得早于披露（DQ-003）、outcome 标签不得
  早于窗口结束（DQ-006）、文档按 (content_hash, parser_version) 去重（DQ-002）、
  事件指纹唯一（FR-R-005）、指标口径按 (metric_id, version) 版本化、
  观测值五元组唯一（DQ-004）。
- downgrade 完整实现，不留空：CI 会跑 upgrade → downgrade base → upgrade 往返。
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('audit_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('actor', sa.String(length=64), nullable=False),
        sa.Column('action', sa.String(length=64), nullable=False),
        sa.Column('object_type', sa.String(length=64), nullable=False),
        sa.Column('object_id', sa.String(length=64), nullable=False),
        sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('model_version', sa.String(length=64), nullable=True),
        sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
        )
        op.create_index('ix_audit_actor_time', 'audit_log', ['actor', 'occurred_at'], unique=False)
        op.create_index('ix_audit_object', 'audit_log', ['object_type', 'object_id'], unique=False)
        op.create_table('data_quality_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rule_id', sa.String(length=32), nullable=False),
        sa.Column('object_type', sa.String(length=64), nullable=False),
        sa.Column('object_id', sa.String(length=64), nullable=True),
        sa.Column('severity', sa.String(length=16), nullable=False),
        sa.Column('passed', sa.Boolean(), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('quarantined', sa.Boolean(), nullable=False),
        sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_result'))
        )
        op.create_index('ix_dq_rule_passed', 'data_quality_result', ['rule_id', 'passed'], unique=False)
        op.create_table('experiment',
        sa.Column('experiment_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('economic_hypothesis', sa.Text(), nullable=False, comment='必须先写经济假设再看结果'),
        sa.Column('signal_type', sa.String(length=64), nullable=True),
        sa.Column('model_version', sa.String(length=64), nullable=False),
        sa.Column('prompt_version', sa.String(length=64), nullable=True),
        sa.Column('dataset_version', sa.String(length=64), nullable=False),
        sa.Column('baseline_name', sa.String(length=128), nullable=False),
        sa.Column('in_sample_range', sa.String(length=64), nullable=True),
        sa.Column('out_sample_range', sa.String(length=64), nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=True, comment='仅有百分比、没有样本数的结果不得用于验收'),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('conclusion_level', sa.String(length=32), nullable=False),
        sa.Column('limitations', sa.Text(), nullable=False, comment='必须披露限制与失败案例'),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('experiment_id', name=op.f('pk_experiment'))
        )
        op.create_table('metric',
        sa.Column('metric_id', sa.String(length=64), nullable=False),
        sa.Column('version', sa.String(length=16), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=64), nullable=True),
        sa.Column('definition', sa.Text(), nullable=True),
        sa.Column('formula', sa.Text(), nullable=True),
        sa.Column('unit', sa.String(length=32), nullable=False),
        sa.Column('frequency', sa.String(length=32), nullable=True),
        sa.Column('period_type', sa.String(length=16), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=True),
        sa.Column('expected_direction', sa.String(length=32), nullable=True),
        sa.Column('allow_yoy', sa.Boolean(), nullable=False),
        sa.Column('allow_qoq', sa.Boolean(), nullable=False),
        sa.Column('allow_peer', sa.Boolean(), nullable=False),
        sa.Column('missing_policy', sa.Text(), nullable=True),
        sa.Column('confirmed_by', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('metric_id', 'version', name=op.f('pk_metric'))
        )
        op.create_table('metric_alias',
        sa.Column('alias', sa.String(length=64), nullable=False),
        sa.Column('metric_id', sa.String(length=64), nullable=False),
        sa.Column('source_note', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('alias', name=op.f('pk_metric_alias'))
        )
        op.create_table('metric_observation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('security_id', sa.String(length=64), nullable=False),
        sa.Column('metric_id', sa.String(length=64), nullable=False),
        sa.Column('metric_version', sa.String(length=16), nullable=False),
        sa.Column('period', sa.String(length=32), nullable=False),
        sa.Column('period_type', sa.String(length=16), nullable=False),
        sa.Column('observation_date', sa.Date(), nullable=False),
        sa.Column('actual_value', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('raw_value', sa.String(length=64), nullable=True),
        sa.Column('unit', sa.String(length=32), nullable=False),
        sa.Column('expected_value', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('benchmark_value', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('source_document_id', sa.String(length=64), nullable=True),
        sa.Column('data_version', sa.String(length=64), nullable=True),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_observation')),
        sa.UniqueConstraint('security_id', 'metric_id', 'metric_version', 'period', 'data_version', name=op.f('uq_metric_observation_security_id'))
        )
        op.create_index('ix_metric_obs_lookup', 'metric_observation', ['security_id', 'metric_id', 'observation_date'], unique=False)
        op.create_table('security',
        sa.Column('security_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('ticker', sa.String(length=32), nullable=True),
        sa.Column('industry', sa.String(length=128), nullable=True),
        sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False, comment='虚构演示数据标记，禁止用于真实投资结论'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('security_id', name=op.f('pk_security'))
        )
        op.create_table('document',
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=512), nullable=True),
        sa.Column('source_id', sa.String(length=64), nullable=True),
        sa.Column('doc_type', sa.String(length=64), nullable=True),
        sa.Column('security_id', sa.String(length=64), nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='首次公开可得时间，收益标签时间起点（FLD-002）'),
        sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256，用于去重与版本追踪（FLD-003）'),
        sa.Column('parser_version', sa.String(length=32), nullable=False),
        sa.Column('raw_path', sa.String(length=1024), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('visibility_label', sa.String(length=32), nullable=False, comment='权限标签；证据可见性不得高于来源文档'),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_document_security_id_security')),
        sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document')),
        sa.UniqueConstraint('content_hash', 'parser_version', name=op.f('uq_document_content_hash'))
        )
        op.create_index('ix_document_published_at', 'document', ['published_at'], unique=False)
        op.create_table('document_segment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=False),
        sa.Column('locator', sa.String(length=128), nullable=False),
        sa.Column('ordinal', sa.Integer(), nullable=False),
        sa.Column('page', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], name=op.f('fk_document_segment_document_id_document'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_document_segment')),
        sa.UniqueConstraint('document_id', 'locator', name=op.f('uq_document_segment_document_id'))
        )
        op.create_table('event',
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('document_id', sa.String(length=64), nullable=True),
        sa.Column('security_id', sa.String(length=64), nullable=True),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('occurred_on', sa.Date(), nullable=True, comment='事实发生时间，无法确认时可为空'),
        sa.Column('disclosure_time', sa.DateTime(timezone=True), nullable=False, comment='首次公开可得时间，必填（FLD-006）；防未来数据泄露关键字段'),
        sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('fingerprint', sa.String(length=64), nullable=False, comment='事件指纹，同一事实多源转载去重'),
        sa.Column('source_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='重复事件合并后保留的来源集合（FR-R-005）'),
        sa.Column('version', sa.String(length=16), nullable=False),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], name=op.f('fk_event_document_id_document')),
        sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_event_security_id_security')),
        sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event')),
        sa.UniqueConstraint('fingerprint', name=op.f('uq_event_fingerprint'))
        )
        op.create_index('ix_event_disclosure_time', 'event', ['disclosure_time'], unique=False)
        op.create_table('thesis',
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('security_id', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('direction', sa.String(length=16), nullable=False),
        sa.Column('core_view', sa.Text(), nullable=False),
        sa.Column('established_on', sa.Date(), nullable=False, comment='逻辑建立日；失效条件的连续期数判定必须按此日期裁剪观察窗口'),
        sa.Column('horizon_end_on', sa.Date(), nullable=True),
        sa.Column('next_review_at', sa.Date(), nullable=True),
        sa.Column('owner', sa.String(length=64), nullable=False),
        sa.Column('visibility', sa.String(length=16), nullable=False),
        sa.Column('team', sa.String(length=64), nullable=True, comment='归属团队；visibility=团队 时的可见范围判断依据，缺失则同组也看不到'),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('invalidation_require_all', sa.Boolean(), nullable=False, comment='thesis 级失效条件是「全部满足」还是「任一满足」。默认 AND：把 AND 当 OR 会让单指标不达标就判失效，误报比漏报更伤信任'),
        sa.Column('source_document_id', sa.String(length=64), nullable=True),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.CheckConstraint('char_length(title) <= 120', name=op.f('ck_thesis_title_len')),
        sa.CheckConstraint('version >= 0', name=op.f('ck_thesis_version_nonneg')),
        sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], name=op.f('fk_thesis_security_id_security')),
        sa.ForeignKeyConstraint(['source_document_id'], ['document.document_id'], name=op.f('fk_thesis_source_document_id_document')),
        sa.PrimaryKeyConstraint('thesis_id', name=op.f('pk_thesis'))
        )
        op.create_index('ix_thesis_owner', 'thesis', ['owner'], unique=False)
        op.create_index('ix_thesis_status', 'thesis', ['status'], unique=False)
        op.create_table('hypothesis',
        sa.Column('hypothesis_id', sa.String(length=64), nullable=False),
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('parent_id', sa.String(length=64), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('statement', sa.Text(), nullable=False),
        sa.Column('hypothesis_type', sa.String(length=32), nullable=False),
        sa.Column('importance', sa.String(length=16), nullable=False),
        sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('observation_window', sa.String(length=128), nullable=True),
        sa.Column('expected_direction', sa.String(length=32), nullable=True),
        sa.Column('invalidation_rule', sa.Text(), nullable=True, comment='失效条件文本，不可由 AI 直接生效（FLD-005）'),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('owner_note', sa.Text(), nullable=True),
        sa.Column('confirmed_by', sa.String(length=64), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['hypothesis.hypothesis_id'], name=op.f('fk_hypothesis_parent_id_hypothesis')),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_hypothesis_thesis_id_thesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('hypothesis_id', name=op.f('pk_hypothesis'))
        )
        op.create_index('ix_hypothesis_thesis_id', 'hypothesis', ['thesis_id'], unique=False)
        op.create_table('review_task',
        sa.Column('task_id', sa.String(length=64), nullable=False),
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('trigger', sa.String(length=32), nullable=False, comment='到期/重大事件/失效条件/人工发起'),
        sa.Column('priority', sa.String(length=16), nullable=False),
        sa.Column('assignee', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('resolution', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_review_task_thesis_id_thesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('task_id', name=op.f('pk_review_task'))
        )
        op.create_index('ix_review_task_state', 'review_task', ['state', 'assignee'], unique=False)
        op.create_table('status_suggestion_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('current_status', sa.String(length=16), nullable=False),
        sa.Column('suggested_status', sa.String(length=16), nullable=False),
        sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('triggered_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('rule_version', sa.String(length=32), nullable=False),
        sa.Column('human_action', sa.String(length=16), nullable=True, comment='接受/拒绝/修改；未处置为空'),
        sa.Column('human_reason', sa.Text(), nullable=True),
        sa.Column('acted_by', sa.String(length=64), nullable=True),
        sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_status_suggestion_log_thesis_id_thesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_status_suggestion_log'))
        )
        op.create_index('ix_status_suggestion_thesis', 'status_suggestion_log', ['thesis_id'], unique=False)
        op.create_table('thesis_version',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='卡片全字段快照，冻结当时可得信息'),
        sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('change_reason', sa.Text(), nullable=True),
        sa.Column('triggered_by', sa.String(length=32), nullable=False, comment='发布/字段修改/证据确认/状态变更/复核'),
        sa.Column('created_by', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_thesis_version_thesis_id_thesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_thesis_version')),
        sa.UniqueConstraint('thesis_id', 'version', name=op.f('uq_thesis_version_thesis_id'))
        )
        op.create_table('evidence',
        sa.Column('evidence_id', sa.String(length=64), nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=True),
        sa.Column('thesis_id', sa.String(length=64), nullable=False),
        sa.Column('hypothesis_id', sa.String(length=64), nullable=False, comment='至少关联一条假设；方向相对假设判断，不是通用情绪'),
        sa.Column('evidence_type', sa.String(length=32), nullable=False),
        sa.Column('direction', sa.String(length=16), nullable=False),
        sa.Column('strength', sa.String(length=16), nullable=True),
        sa.Column('strength_score', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('horizon', sa.String(length=16), nullable=True),
        sa.Column('is_direct', sa.Boolean(), nullable=True),
        sa.Column('evidence_locator', sa.String(length=255), nullable=False, comment='必须能打开原文，格式 {document_id}#paragraph-{n}'),
        sa.Column('transmission_path', sa.Text(), nullable=True),
        sa.Column('ai_status', sa.String(length=16), nullable=True),
        sa.Column('ai_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('model_version', sa.String(length=64), nullable=True),
        sa.Column('prompt_version', sa.String(length=64), nullable=True),
        sa.Column('confirmation_status', sa.String(length=16), nullable=False),
        sa.Column('review_status', sa.String(length=16), nullable=True),
        sa.Column('review_note', sa.Text(), nullable=True),
        sa.Column('confirmed_by', sa.String(length=64), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_evidence_event_id_event')),
        sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.hypothesis_id'], name=op.f('fk_evidence_hypothesis_id_hypothesis')),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_evidence_thesis_id_thesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence'))
        )
        op.create_index('ix_evidence_hypothesis', 'evidence', ['hypothesis_id'], unique=False)
        op.create_index('ix_evidence_thesis', 'evidence', ['thesis_id', 'confirmation_status'], unique=False)
        op.create_table('hypothesis_metric_map',
        sa.Column('mapping_id', sa.String(length=64), nullable=False),
        sa.Column('hypothesis_id', sa.String(length=64), nullable=False),
        sa.Column('metric_id', sa.String(length=64), nullable=False),
        sa.Column('metric_version', sa.String(length=16), nullable=False),
        sa.Column('metric_role', sa.String(length=16), nullable=True),
        sa.Column('expected_direction', sa.String(length=32), nullable=False),
        sa.Column('expected_value', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('expected_lower', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('expected_upper', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('expectation_source', sa.String(length=255), nullable=True, comment='预期来源，预期差计算要求可追溯（GAP-002）'),
        sa.Column('expectation_recorded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('validation_rule', sa.Text(), nullable=True),
        sa.Column('invalidation_rule', sa.Text(), nullable=True),
        sa.Column('invalidation_threshold', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('observation_frequency', sa.String(length=32), nullable=True),
        sa.Column('confirmation_status', sa.String(length=16), nullable=False),
        sa.Column('confirmed_by', sa.String(length=64), nullable=True),
        sa.Column('version', sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.hypothesis_id'], name=op.f('fk_hypothesis_metric_map_hypothesis_id_hypothesis'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('mapping_id', name=op.f('pk_hypothesis_metric_map'))
        )
        op.create_index('ix_hmm_hypothesis_id', 'hypothesis_metric_map', ['hypothesis_id'], unique=False)
        op.create_table('signal',
        sa.Column('signal_id', sa.String(length=64), nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=True),
        sa.Column('thesis_id', sa.String(length=64), nullable=True),
        sa.Column('hypothesis_id', sa.String(length=64), nullable=True),
        sa.Column('security_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('direction', sa.String(length=16), nullable=False, comment='对关联假设的影响方向，不等于股价方向'),
        sa.Column('strength', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('horizon', sa.String(length=16), nullable=True),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('available_at', sa.DateTime(timezone=True), nullable=False, comment='首次可得时间，收益窗口起点依据'),
        sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='模型生成时间；必须晚于或等于披露时间（DQ-003）'),
        sa.Column('model_version', sa.String(length=64), nullable=False),
        sa.Column('prompt_version', sa.String(length=64), nullable=False),
        sa.Column('evidence_locator', sa.String(length=255), nullable=True, comment='DQ-005：正式信号必须有证据定位和模型版本'),
        sa.Column('human_verdict', sa.String(length=16), nullable=True),
        sa.Column('human_direction', sa.String(length=16), nullable=True),
        sa.Column('reject_reason', sa.Text(), nullable=True),
        sa.Column('in_experiment', sa.Boolean(), nullable=False),
        sa.Column('version', sa.String(length=16), nullable=False),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.CheckConstraint('generated_at >= available_at', name=op.f('ck_signal_no_future_leakage')),
        sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], name=op.f('fk_signal_event_id_event')),
        sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.hypothesis_id'], name=op.f('fk_signal_hypothesis_id_hypothesis')),
        sa.ForeignKeyConstraint(['thesis_id'], ['thesis.thesis_id'], name=op.f('fk_signal_thesis_id_thesis')),
        sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_signal'))
        )
        op.create_index('ix_signal_generated_at', 'signal', ['generated_at'], unique=False)
        op.create_table('outcome',
        sa.Column('outcome_id', sa.String(length=64), nullable=False),
        sa.Column('signal_id', sa.String(length=64), nullable=False),
        sa.Column('security_id', sa.String(length=64), nullable=False),
        sa.Column('window_start_on', sa.Date(), nullable=False, comment='首次可得时间的下一可交易时点'),
        sa.Column('window_end_on', sa.Date(), nullable=False),
        sa.Column('window_days', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.Column('fundamental_result', sa.Text(), nullable=True),
        sa.Column('fundamental_realized', sa.String(length=16), nullable=True),
        sa.Column('security_return', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('benchmark_return', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('excess_return', sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column('benchmark_id', sa.String(length=64), nullable=True),
        sa.Column('is_hit', sa.Boolean(), nullable=True),
        sa.Column('label_generated_at', sa.Date(), nullable=True),
        sa.Column('data_version', sa.String(length=64), nullable=True),
        sa.Column('is_illustrative', sa.Boolean(), nullable=False),
        sa.CheckConstraint('label_generated_at IS NULL OR label_generated_at >= window_end_on', name=op.f('ck_outcome_no_label_before_window_end')),
        sa.CheckConstraint('window_end_on >= window_start_on', name=op.f('ck_outcome_window_order')),
        sa.ForeignKeyConstraint(['signal_id'], ['signal.signal_id'], name=op.f('fk_outcome_signal_id_signal'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('outcome_id', name=op.f('pk_outcome'))
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('outcome')
        op.drop_index('ix_signal_generated_at', table_name='signal')
        op.drop_table('signal')
        op.drop_index('ix_hmm_hypothesis_id', table_name='hypothesis_metric_map')
        op.drop_table('hypothesis_metric_map')
        op.drop_index('ix_evidence_thesis', table_name='evidence')
        op.drop_index('ix_evidence_hypothesis', table_name='evidence')
        op.drop_table('evidence')
        op.drop_table('thesis_version')
        op.drop_index('ix_status_suggestion_thesis', table_name='status_suggestion_log')
        op.drop_table('status_suggestion_log')
        op.drop_index('ix_review_task_state', table_name='review_task')
        op.drop_table('review_task')
        op.drop_index('ix_hypothesis_thesis_id', table_name='hypothesis')
        op.drop_table('hypothesis')
        op.drop_index('ix_thesis_status', table_name='thesis')
        op.drop_index('ix_thesis_owner', table_name='thesis')
        op.drop_table('thesis')
        op.drop_index('ix_event_disclosure_time', table_name='event')
        op.drop_table('event')
        op.drop_table('document_segment')
        op.drop_index('ix_document_published_at', table_name='document')
        op.drop_table('document')
        op.drop_table('security')
        op.drop_index('ix_metric_obs_lookup', table_name='metric_observation')
        op.drop_table('metric_observation')
        op.drop_table('metric_alias')
        op.drop_table('metric')
        op.drop_table('experiment')
        op.drop_index('ix_dq_rule_passed', table_name='data_quality_result')
        op.drop_table('data_quality_result')
        op.drop_index('ix_audit_object', table_name='audit_log')
        op.drop_index('ix_audit_actor_time', table_name='audit_log')
        op.drop_table('audit_log')
        # ### end Alembic commands ###
